app/modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

class UserController extends Controller
{
    public function actionIndex()
    {
        $users = User::find()
            ->where(['!=', 'id', \Yii::$app->user->identity->getId()]);

        return $this->render('index', compact('users'));
    }

    public function actionEdit($user_id = null)
    {
        $user = is_null($user_id)
            ? \Yii::createObject(User::class)
            : User::findOne($user_id);

        if (\Yii::$app->request->getIsPost()) {
            $user->load(\Yii::$app->request->post());
            if (!$user->save()) {
                \Yii::$app->session->setFlash('edit.warning', \Yii::t('app', current($user->firstErrors)));
            } elseif (!empty($user_id)) {
                \Yii::$app->session->setFlash('edit.success', \Yii::t('app', 'User saved'));
                return $this->refresh();
            }

            return $this->redirect(['user/index']);
        }

        return $this->render('edit', compact('user'));
    }

    public function actionDelete($user_id)
    {
        if (!$user = User::findOne($user_id)) {
            throw new NotFoundHttpException(\Yii::t('app', 'User not found'));
        } elseif (!$user->delete()) {
            throw new ServerErrorHttpException("Can't delete user");
        }

        return $this->redirect(\Yii::$app->request->getReferrer());
    }
}

app/modules/admin/views/user/edit.php
<?php
/**
 * @var \yii\web\View $this
 * @var \app\models\User $user
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = Yii::t('app', 'User management');
?>

<h1><?= Html::encode($this->title) ?></h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <?php $form = ActiveForm::begin() ?>
            <div class="panel-body">
                <?php if (Yii::$app->session->hasFlash('edit.warning')): ?>
                    <div class="alert alert-danger">
                        <?= Yii::$app->session->getFlash('edit.warning') ?>
                    </div>
                <?php elseif (Yii::$app->session->hasFlash('edit.success')): ?>
                    <div class="alert alert-success">
                        <?= Yii::$app->session->getFlash('edit.success') ?>
                    </div>
                <?php endif; ?>

                <?= $form->field($user, 'login')
                    ->input('email', ['placeholder' => 'Email']) ?>

                <?= $form->field($user, 'password')
                    ->passwordInput() ?>

                <?= $form->field($user, 'password_retype')
                    ->passwordInput() ?>
            </div>
            <div class="panel-footer">
                <?= Html::submitButton(Yii::t('app', 'Apply'),
                    ['class' => ['btn', 'btn-primary', 'btn-lg']]) ?>
            </div>
            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>

app/modules/admin/views/user/index.php
<?php
/**
 * @var \yii\web\View $this
 * @var \yii\db\ActiveQuery $users
 */

use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Users list');

?>
<h1 class="page-header"><?= Html::encode($this->title) ?></h1>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <?= GridView::widget([
            'dataProvider' => new ActiveDataProvider([
                'query' => $users,
            ]),
            'columns' => [
                [
                    'class' => \yii\grid\SerialColumn::class,
                ],
                [
                    'attribute' => 'login',
                    'content' => function (\app\models\User $user) {
                        return Html::a($user->login, ['user/edit', 'user_id' => $user->id]);
                    },
                ],
                'created_at:datetime',
                'updated_at:datetime',
                [
                    'content' => function (\app\models\User $user) {
                        return Html::a('Delete', ['user/delete', 'user_id' => $user->id],
                            [
                                'class' => ['btn', 'btn-xs', 'btn-danger'],
                                'onclick' => new \yii\web\JsExpression('return window.confirm("' . Yii::t('app', 'Confirm operation!') . '")'),
                            ]);
                    }
                ],
            ],
        ]) ?>
        <?= Html::a(Yii::t('app', 'Create new user'), ['user/edit'],
            ['class' => ['btn', 'btn-primary']]) ?>
    </div>
</div>